version: '3.9'
services:
  json-server:
    image: clue/json-server:${VERSION}
    container_name: ${NAME}
    networks:
      json_server_bridge:
        ipv4_address: ${IP}
    ports:
      - ${PORT}:80
    volumes:
      - ./db.json:/data/db.json
    command: -w /data/db.json

networks:
  json_server_bridge:
    external: true
    name: json_server_bridge